"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { Icon } from "./icon";

export function ConversationCreateForm({ type }: { type: "group" | "channel" }) {
  const router = useRouter(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [slug, setSlug] = useState(""); const [visibility, setVisibility] = useState<"public" | "private">("private"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const isChannel = type === "channel";
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/conversations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, title, description, slug: slug || undefined, visibility, memberIds: [] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "ساخت گفت‌وگو ممکن نشد"); router.push(`/chat/${body.conversation.id}`); } catch (err) { setError(err instanceof Error ? err.message : "ساخت گفت‌وگو ممکن نشد"); } finally { setLoading(false); } }
  return <form className="settings-section settings-form" onSubmit={submit}><div><span className="eyebrow">NEW {isChannel ? "CHANNEL" : "GROUP"}</span><h2>{isChannel ? "ساخت کانال" : "ساخت گروه"}</h2><p>{isChannel ? "برای انتشار پیام به اعضای خودت یک کانال بساز." : "یک فضای گفت‌وگوی مشترک برای دوستانت بساز."}</p></div><div className="field"><label htmlFor="conversation-title">نام</label><input id="conversation-title" className="input" value={title} onChange={(event) => setTitle(event.target.value)} required maxLength={100} /></div><div className="field"><label htmlFor="conversation-description">توضیح</label><textarea id="conversation-description" className="textarea" value={description} onChange={(event) => setDescription(event.target.value)} maxLength={500} /></div><div className="field"><label htmlFor="conversation-slug">شناسه عمومی اختیاری</label><input id="conversation-slug" className="input mono" dir="ltr" value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase())} placeholder="my_channel" pattern="[a-z0-9_]{3,48}" /><span className="field-hint">برای عمومی شدن، یک شناسه یکتا با حروف انگلیسی وارد کن.</span></div><div className="field"><label htmlFor="conversation-visibility">دسترسی</label><select id="conversation-visibility" className="select" value={visibility} onChange={(event) => setVisibility(event.target.value as "public" | "private")}><option value="private">خصوصی؛ فقط با دعوت</option><option value="public">عمومی؛ قابل جست‌وجو</option></select></div>{error && <p className="field-hint" role="alert" style={{ color: "var(--danger)" }}>{error}</p>}<button className="button button--primary" disabled={loading || !title.trim()} type="submit"><Icon name="plus" size={17} />{loading ? "…" : isChannel ? "ساخت کانال" : "ساخت گروه"}</button></form>;
}
