"use client";

import { useEffect, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { Icon } from "../../components/icon";
import { usePreferences, useSessionUser } from "../../components/data-hooks";

type Tab = "profile" | "notifications" | "privacy";

export default function SettingsPage() {
  const [tab, setTab] = useState<Tab>("profile"); const { data: preferences, update } = usePreferences(); const { user, setUser } = useSessionUser(); const [displayName, setDisplayName] = useState(""); const [bio, setBio] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (user) { setDisplayName(user.displayName); setBio(user.bio ?? ""); } }, [user]);
  async function saveProfile() { setSaving(true); setError(""); try { const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName, bio, language: preferences.language }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "ذخیره انجام نشد"); setUser(body.user); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } catch (err) { setError(err instanceof Error ? err.message : "ذخیره انجام نشد"); } finally { setSaving(false); } }
  async function uploadAvatar(file?: File) { if (!file) return; const form = new FormData(); form.set("file", file); const response = await fetch("/api/profile/avatar", { method: "POST", body: form }); const body = await response.json(); if (response.ok) setUser(body.user); else setError(body.error ?? "آپلود انجام نشد"); }
  return <AppShell title="تنظیمات" hint="حساب و تجربه کاربری"><div className="section-heading"><div><span className="eyebrow mono">PREFERENCES</span><h1>تنظیمات حساب</h1><p>کنترل ساده و شفاف برای فضای شخصی تو.</p></div></div><div className="settings-layout"><nav className="settings-tabs" aria-label="بخش‌های تنظیمات"><button className="settings-tab" aria-selected={tab === "profile"} onClick={() => setTab("profile")}><Icon name="user" size={18} />پروفایل</button><button className="settings-tab" aria-selected={tab === "notifications"} onClick={() => setTab("notifications")}><Icon name="bell" size={18} />اعلان‌ها</button><button className="settings-tab" aria-selected={tab === "privacy"} onClick={() => setTab("privacy")}><Icon name="lock" size={18} />حریم خصوصی</button></nav><div className="settings-panel">
    {tab === "profile" && <section className="settings-section" aria-labelledby="profile-heading"><h2 id="profile-heading">پروفایل</h2><p>اطلاعاتی که دیگران در گفت‌وگوها می‌بینند.</p><div className="settings-form"><div className="profile-chip"><span className="avatar avatar--large">{(displayName || "ش").slice(0, 1)}</span><label className="button" htmlFor="avatar-upload">تغییر عکس<input id="avatar-upload" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden onChange={(event) => uploadAvatar(event.target.files?.[0])} /></label></div><div className="field"><label htmlFor="display-name">نام نمایشی</label><input className="input" id="display-name" value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></div><div className="field"><label htmlFor="username">نام کاربری</label><input className="input mono" id="username" value={user ? `@${user.username}` : ""} readOnly dir="ltr" /><span className="field-hint">نام کاربری پس از ثبت‌نام ثابت است.</span></div><div className="field"><label htmlFor="bio">معرفی کوتاه</label><textarea className="textarea" id="bio" value={bio} onChange={(event) => setBio(event.target.value)} /></div>{error && <p className="field-hint" role="alert" style={{ color: "var(--danger)" }}>{error}</p>}<div><button className="button button--primary" onClick={saveProfile} disabled={saving}>{saving ? "…" : "ذخیره تغییرات"}</button>{saved && <span className="field-hint" role="status"> تغییرات ذخیره شد.</span>}</div></div></section>}
    {tab === "notifications" && <section className="settings-section" aria-labelledby="notifications-heading"><h2 id="notifications-heading">اعلان‌ها</h2><p>انتخاب کن چه زمانی از پیام‌های تازه باخبر شوی.</p><div className="setting-row"><div><p>اعلان پیام‌های جدید</p><small>برای هر پیام خوانده‌نشده اعلان دریافت کن.</small></div><Toggle on={preferences.notifications} onChange={(value) => update({ notifications: value })} /></div><div className="setting-row"><div><p>اعلان دسکتاپ</p><small>حتی وقتی پنجره فعال نیست، خبرت می‌کنیم.</small></div><Toggle on={preferences.desktopAlerts} onChange={(value) => update({ desktopAlerts: value })} /></div></section>}
    {tab === "privacy" && <section className="settings-section" aria-labelledby="privacy-heading"><h2 id="privacy-heading">حریم خصوصی</h2><p>کنترل کن دیگران چه اطلاعاتی از تعامل تو ببینند.</p><div className="setting-row"><div><p>تأیید خوانده‌شدن</p><small>فرستنده بداند پیامش را دیده‌ای.</small></div><Toggle on={preferences.readReceipts} onChange={(value) => update({ readReceipts: value })} /></div><div className="setting-row"><div><p>زبان رابط</p><small>با تغییر زبان، انتخاب در همین مرورگر ذخیره می‌شود.</small></div><select className="select" style={{ width: 120 }} value={preferences.language} onChange={(event) => update({ language: event.target.value as "fa" | "en" })}><option value="fa">فارسی</option><option value="en">English</option></select></div></section>}
  </div></div></AppShell>;
}
function Toggle({ on, onChange }: { on: boolean; onChange: (value: boolean) => void }) { return <button type="button" className="toggle" data-on={on} aria-pressed={on} onClick={() => onChange(!on)} aria-label={on ? "غیرفعال کردن" : "فعال کردن"}><span /></button>; }
