"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../../../../components/app-shell";
import { Icon } from "../../../../components/icon";

export default function ConversationSettingsPage({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [conversation, setConversation] = useState<any>(null); const [username, setUsername] = useState(""); const [suggestions, setSuggestions] = useState<any[]>([]); const [error, setError] = useState("");
  async function load(value: string) { const response = await fetch(`/api/conversations/${value}`); const body = await response.json(); if (response.ok) setConversation(body.conversation); else setError(body.error ?? "گفت‌وگو پیدا نشد"); }
  useEffect(() => { params.then(({ id: value }) => { setId(value); void load(value); }); }, [params]);
  async function search(value: string) { setUsername(value); if (value.length < 2) return setSuggestions([]); const response = await fetch(`/api/users/search?q=${encodeURIComponent(value)}`); const body = await response.json(); setSuggestions(body.users ?? []); }
  async function addMember(userId: string) { const response = await fetch(`/api/conversations/${id}/members`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId }) }); if (!response.ok) { const body = await response.json(); setError(body.error ?? "افزودن عضو انجام نشد"); return; } setUsername(""); setSuggestions([]); await load(id); }
  async function removeMember(userId: string) { const response = await fetch(`/api/conversations/${id}/members`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId }) }); if (!response.ok) { const body = await response.json(); setError(body.error ?? "حذف عضو انجام نشد"); return; } await load(id); }
  return <AppShell title="مدیریت گفت‌وگو" hint="اعضا و دسترسی‌ها"><div className="section-heading"><div><Link href={`/chat/${id}`} className="button button--ghost"><Icon name="arrow-right" size={16} />بازگشت به گفت‌وگو</Link><h1>{conversation?.title ?? "مدیریت گفت‌وگو"}</h1><p>نقش‌ها و اعضای این گفت‌وگو را مدیریت کن.</p></div></div>{error && <p role="alert" className="field-hint" style={{ color: "var(--danger)" }}>{error}</p>}<section className="settings-section"><h2>افزودن عضو</h2><p>با نام کاربری جست‌وجو کن و عضو اضافه کن.</p><div className="field"><label htmlFor="member-search">نام کاربری</label><input id="member-search" className="input mono" dir="ltr" value={username} onChange={(event) => search(event.target.value)} placeholder="username" /></div>{suggestions.length > 0 && <div className="conversation-list">{suggestions.map((item) => <button className="conversation-item" type="button" key={item.id} onClick={() => addMember(item.id)}><span className="avatar">{item.displayName.slice(0, 1)}</span><span className="conversation-item-main"><strong className="conversation-item-name">{item.displayName}</strong><span className="conversation-item-preview">@{item.username}</span></span><Icon name="plus" size={18} /></button>)}</div>}</section><section className="settings-section"><h2>اعضا</h2><p>{conversation?.members?.length ?? 0} عضو</p><div className="conversation-list">{(conversation?.members ?? []).map((member: any) => <div className="conversation-item" key={member.userId}><span className="avatar">{member.user?.displayName?.slice(0, 1) ?? "؟"}</span><span className="conversation-item-main"><strong className="conversation-item-name">{member.user?.displayName ?? member.userId}</strong><span className="conversation-item-preview">@{member.user?.username ?? ""} · {member.role}</span></span>{member.role !== "owner" && <button type="button" className="icon-button" aria-label="حذف عضو" onClick={() => removeMember(member.userId)}><Icon name="close" size={16} /></button>}</div>)}</div></section></AppShell>;
}
